[package]
name = "invar"
description = "CLI management tool for modded Minecraft servers"
version = "0.3.0"
edition = "2021"
authors = ["mxxntype <59417007+mxxntype@users.noreply.github.com>"]
homepage = "https://github.com/exoumoon/invar"
license-file = "LICENSE"

[[bin]]
name = "invar"
path = "src/cli/main.rs"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
complexity = "warn"
perf = "warn"
enum_glob_use = { level = "warn", priority = 1 }
single_match_else = { level = "allow", priority = 1 }
option_if_let_else = { level = "allow", priority = 1 }
or_fun_call = { level = "allow", priority = 1 }
match_bool = { level = "allow", priority = 1 }

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.17", features = ["derive", "color"] }
color-eyre = "0.6.3"
eyre = "0.6.12"
inquire = "0.7.5"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_with = { version = "3.9.0", features = ["hex"] }
serde_yml = "0.0.12"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.64"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
url = { version = "2.5.2", features = ["serde"] }
walkdir = "2.5.0"
zip = { version = "2.2.0", features = ["deflate-flate2"] }
