[package]
name = "invar-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.3.2"
chrono = { version = "0.4.39", features = ["serde"] }
color-eyre = "0.6.3"
copy_dir = "0.1.3"
docker-compose-types = { version = "0.15.0", default-features = false, features = [
    "yml",
] }
eyre = "0.6.12"
indoc = "2.0.5"
invar-pack = { version = "0.6.0", path = "../invar-pack" }
invar-repository = { version = "0.1.0", path = "../invar-repository" }
itertools = "0.14.0"
serde = { version = "1.0.217", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "2.0.11"
tracing = "0.1.41"

[lints]
workspace = true
